(() => {
  'use strict';
  const VOCAB = Array.isArray(window.ITALIANO_VOCAB) ? window.ITALIANO_VOCAB : [];
  const KEY = 'neonItaliano_v1';
  const DAY = 86400000, MINUTE = 60000;
  const defaultState = { xp:0, streak:1, lastDay:'', mood:'pronto', current:0, reviews:{}, known:{}, signals:{}, stats:{seen:0,correct:0,blurts:0,hunts:0,productions:0,stories:0} };
  let state;
  try { state = {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}; } catch(_) { state={...defaultState}; }
  state.reviews ||= {}; state.known ||= {}; state.signals ||= {}; state.stats={...defaultState.stats,...(state.stats||{})};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], save=()=>localStorage.setItem(KEY,JSON.stringify(state)), today=()=>new Date().toISOString().slice(0,10);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function updateStreak(){const t=today();if(!state.lastDay)state.lastDay=t;else if(state.lastDay!==t){const d=Math.round((new Date(t)-new Date(state.lastDay))/DAY);state.streak=d===1?(state.streak||1)+1:1;state.lastDay=t;}}
  function dueCount(){const now=Date.now();return VOCAB.reduce((n,_,i)=>n+(state.reviews[i]&&(state.reviews[i].due||0)<=now?1:0),0)}
  function newCount(){return VOCAB.reduce((n,_,i)=>n+(!state.reviews[i]?1:0),0)}
  function nextCardIndex(){const now=Date.now();const due=VOCAB.map((_,i)=>i).filter(i=>state.reviews[i]&&(state.reviews[i].due||0)<=now);if(due.length)return due[Math.floor(Math.random()*due.length)];const fresh=VOCAB.map((_,i)=>i).filter(i=>!state.reviews[i]);if(fresh.length)return fresh[0];return(state.current+1)%Math.max(1,VOCAB.length)}
  function show(screen){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===screen));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===screen));window.scrollTo({top:0,behavior:'smooth'});if(screen==='learn')renderLearn();if(screen==='map')renderMap();if(screen==='srs')renderSrs();if(screen==='blurt')renderBlurt();if(screen==='hunt')newHunt();if(screen==='story')renderStory();if(screen==='statsScreen')renderStats();renderHeader()}
  function renderHeader(){$('#due').textContent=dueCount();$('#xp').textContent=state.xp||0;$('#known').textContent=Object.values(state.known).filter(Boolean).length;$('#streak').textContent=state.streak||1;if($('#srsDue'))$('#srsDue').textContent=dueCount()}
  function currentWord(){return VOCAB[state.current%Math.max(1,VOCAB.length)]||{}}
  function reviewFor(i){return state.reviews[i]||null} function signalFor(i){return state.signals[i]||{blurt:0,production:0,story:0}}
  function masteryLabel(i){const r=reviewFor(i),s=signalFor(i);if(!r)return'🆕 Nouveau';if(r.reps>=3&&(s.blurt>=70||s.production>=1))return'🟢 Actif';if(r.reps>=2)return'🟡 Rappel';return'🔵 Reconnu'}
  function renderLearn(){const w=currentWord(),i=state.current%VOCAB.length,r=reviewFor(i);$('#word').textContent=w.word||'';$('#card').innerHTML=`<h1>${esc(w.word)}</h1><div class="translation">${esc(w.translation)}</div><div class="phonetic">${esc(w.phonetic)} · ${esc(w.level)}</div><div style="margin-top:10px;opacity:.85;font-size:.9rem">${masteryLabel(i)} · ${r?`révisions ${r.reps||0} · intervalle ${formatInterval((r.interval||0)*DAY)}`:'première rencontre'}</div>`;renderTab('memory');updateGradeLabels()}
  function updateGradeLabels(){const i=state.current%VOCAB.length,r=reviewFor(i),buttons=$$('[data-grade]');if(!buttons.length)return;if(!r||!r.reps){buttons[0].innerHTML='🔴 Encore <small>10 min</small>';buttons[1].innerHTML='🟠 Difficile <small>1 j</small>';buttons[2].innerHTML='🟡 Bien <small>3 j</small>';buttons[3].innerHTML='🟢 Facile <small>7 j</small>';return}buttons[0].innerHTML='🔴 Encore <small>10 min</small>';buttons[1].innerHTML=`🟠 Difficile <small>${previewInterval(r,2)}</small>`;buttons[2].innerHTML=`🟡 Bien <small>${previewInterval(r,3)}</small>`;buttons[3].innerHTML=`🟢 Facile <small>${previewInterval(r,4)}</small>`}
  function formatInterval(ms){if(!ms||ms<DAY)return`${Math.max(1,Math.round(ms/MINUTE))} min`;const d=Math.max(1,Math.round(ms/DAY));return d===1?'1 j':`${d} j`}
  function calculateInterval(r,grade){const interval=r.interval||0,ease=r.ease||2.5;if(grade===1)return 10*MINUTE;if(grade===2)return Math.max(DAY,interval?interval*1.2*DAY:DAY);if(!r.reps)return grade===4?7*DAY:3*DAY;if(r.reps===1)return grade===4?10*DAY:6*DAY;const m=grade===4?ease*1.35:grade===3?ease:1.2;return Math.max(DAY,interval*m*DAY)}
  function previewInterval(r,g){return formatInterval(calculateInterval(r,g))}
  function renderTab(tab){const w=currentWord(),i=state.current%VOCAB.length,s=signalFor(i);$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const blocks={memory:`<div class="info"><div><b>🧠 MEMORY HOOK</b>${esc(w.hook)}</div><div><b>🇫🇷 SENS</b>${esc(w.translation)}</div><div><b>🔊 PRONONCIATION</b>${esc(w.phonetic)}</div></div>`,links:`<div class="info"><div><b>🔗 SYNONYMES</b>${esc(w.synonyms||'—')}</div><div><b>↔️ ANTONYMES</b>${esc(w.antonyms||'—')}</div><div><b>🧩 COLLOCATIONS</b>${esc(w.collocations)}</div></div>`,story:`<div class="info"><div><b>🇮🇹 EXEMPLE</b>${esc(w.example)}</div><div><b>🇫🇷 TRADUCTION</b>${esc(w.exampleFr)}</div><div><b>🎭 MINI-STORY</b>${esc(w.story)}</div><div><b>🇫🇷 TRADUCTION</b>${esc(w.storyFr)}</div><button class="continue" id="markStory">✓ J’AI RACONTÉ L’HISTOIRE</button></div>`,speak:`<div class="panel"><b>🗣️ PRODUCTION</b><p>Écoute, répète 3 fois, puis crée une phrase personnelle avec <strong>${esc(w.word)}</strong>.</p><button class="continue" id="speakWord">🔊 ÉCOUTER EN ITALIEN</button><button class="continue" id="markProduction" style="margin-top:8px">✓ J’AI PRODUIT MA PHRASE</button><p class="hint">Production enregistrée : ${s.production||0} fois.</p></div>`};$('#content').innerHTML=blocks[tab];$('#speakWord')?.addEventListener('click',()=>speak(w.example));$('#markProduction')?.addEventListener('click',()=>{const x=signalFor(i);x.production=(x.production||0)+1;state.signals[i]=x;state.stats.productions++;state.xp+=10;save();renderTab('speak');renderHeader()});$('#markStory')?.addEventListener('click',()=>{const x=signalFor(i);x.story=(x.story||0)+1;state.signals[i]=x;state.stats.stories++;state.xp+=8;save();renderTab('story');renderHeader()})}
  function schedule(i,grade){const r=state.reviews[i]||{interval:0,reps:0,ease:2.5},s=signalFor(i);let effective=grade;const blurt=Number(s.blurt||0),production=Number(s.production||0);if(grade>=3&&blurt>=70&&production>=1)effective=Math.min(4,grade+1);else if(grade>=3&&blurt<30&&production===0)effective=Math.max(2,grade-1);const oldEase=r.ease||2.5,nextMs=calculateInterval(r,effective);if(effective===1)r.ease=Math.max(1.3,oldEase-.2);else if(effective===2)r.ease=Math.max(1.3,oldEase-.08);else if(effective===4)r.ease=Math.min(3.2,oldEase+.08);else r.ease=oldEase;r.reps=effective===1?0:(r.reps||0)+1;r.interval=nextMs/DAY;r.lastGrade=grade;r.effectiveGrade=effective;r.lastReviewed=Date.now();r.due=Date.now()+nextMs;r.lapses=(r.lapses||0)+(effective===1?1:0);r.blurt=blurt;r.production=production;r.story=Number(s.story||0);state.reviews[i]=r;if(effective>=3&&r.reps>=2&&(blurt>=40||production>=1))state.known[i]=true;else if(effective===1)delete state.known[i];state.xp+=grade*5+(effective>grade?5:0);state.stats.seen++;if(grade>=3)state.stats.correct++;save();renderHeader()}
  function gradeCurrent(grade){const i=state.current%VOCAB.length;schedule(i,grade);state.signals[i]={blurt:0,production:0,story:0};state.current=nextCardIndex();save();renderLearn()}
  function renderMap(){const select=$('#mapWord');if(!select.options.length)VOCAB.forEach((w,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${w.word} · ${w.translation}`;select.appendChild(o)});select.value=String(state.current%VOCAB.length);drawMap(Number(select.value))}
  function drawMap(i){const w=VOCAB[i],nodes=[[w.word,50,50,'center'],['🧠 Mémoire',23,25,'gold'],['🔗 '+(w.synonyms||'synonymes').split(' · ')[0],78,25,''],['↔️ '+(w.antonyms||'contraire').split(' · ')[0],78,72,''],['🧩 '+(w.collocations||'').split(' · ')[0],22,74,''],['🎭 Story',50,84,'gold']];const lines=nodes.slice(1).map(n=>`<div style="position:absolute;left:50%;top:50%;width:${Math.hypot(n[1]-50,n[2]-50)}%;height:2px;background:#1e5547;transform-origin:left center;transform:rotate(${Math.atan2(n[2]-50,n[1]-50)*180/Math.PI}deg)"></div>`).join('');$('#mapbox').innerHTML=lines+nodes.map((n,k)=>`<button class="node ${n[3]}" style="left:${n[1]}%;top:${n[2]}%" data-node="${k}">${esc(n[0])}</button>`).join('');$$('#mapbox .node').forEach(btn=>btn.addEventListener('click',()=>{state.current=i;show('learn')}))}
  function renderSrs(){const due=dueCount(),fresh=newCount();$('#srsDue').textContent=due;const panel=$('#srsDue')?.closest('.panel');if(panel){const p=panel.querySelector('p');if(p)p.innerHTML=due?`<strong>${due}</strong> carte${due>1?'s':''} à revoir maintenant. ${fresh} nouveau${fresh>1?'x':''} mot${fresh>1?'s':''} reste${fresh>1?'nt':''} disponible${fresh>1?'s':''}.<br><small>Le SRS combine maintenant rappel, production et storytelling.</small>`:`${fresh} nouveau${fresh>1?'x':''} mot${fresh>1?'s':''} disponible${fresh>1?'nt':''}. Les cartes solides s'espacent automatiquement.`}}
  function renderBlurt(){const w=currentWord();$('#blurtWord').textContent=w.word;$('#blurtInput').value='';$('#blurtResult').innerHTML=''}
  function normalize(s){return(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9à-ÿ' ]/gi,' ').replace(/\s+/g,' ').trim()}
  function tokenSet(s){return new Set(normalize(s).split(/\s+/).filter(t=>t.length>2))}
  function fieldRecall(input, target){const targetTokens=tokenSet(target);if(!targetTokens.size)return 0;const inputTokens=tokenSet(input);let hit=0;targetTokens.forEach(t=>{if(inputTokens.has(t))hit++});return Math.min(1,hit/targetTokens.size)}
  function blurtCheck(){
    const i=state.current%VOCAB.length,w=currentWord(),text=$('#blurtInput').value.trim(),s=signalFor(i);
    const meaning=fieldRecall(text,w.translation), synonyms=fieldRecall(text,w.synonyms), collocations=fieldRecall(text,w.collocations), example=fieldRecall(text,w.example), target=fieldRecall(text,w.word);
    const phraseBonus=/\b(sono|sei|è|era|ero|abbiamo|hanno|ho|hai|devo|posso|voglio|mi|ti|si|ci|non|che|per|con|a|di)\b/i.test(text)?1:0;
    const breakdown={meaning:Math.round(meaning*100),synonyms:Math.round(synonyms*100),collocations:Math.round(collocations*100),example:Math.round(example*100),target:Math.round(target*100),production:phraseBonus?100:0};
    const score=Math.round(meaning*25+synonyms*15+collocations*20+example*15+target*10+phraseBonus*15);
    s.blurt=Math.max(s.blurt||0,score);s.blurtBreakdown=breakdown;state.signals[i]=s;state.stats.blurts++;state.xp+=Math.max(5,Math.round(score/5));save();
    const label=score>=80?'🔥 Rappel exceptionnel':score>=60?'🟢 Très bon rappel':score>=40?'🟡 Bon début':'🔵 À renforcer';
    $('#blurtResult').innerHTML=`<div class="panel"><h2>${score}%</h2><p><strong>${label}</strong></p><div class="info"><div><b>🇫🇷 SENS · 25%</b>${breakdown.meaning}%</div><div><b>🔗 SYNONYMES · 15%</b>${breakdown.synonyms}%</div><div><b>🧩 COLLOCATIONS · 20%</b>${breakdown.collocations}%</div><div><b>💬 EXEMPLE · 15%</b>${breakdown.example}%</div><div><b>🎯 MOT CIBLE · 10%</b>${breakdown.target}%</div><div><b>🗣️ PRODUCTION · 15%</b>${breakdown.production}%</div></div><p><strong>Attendu :</strong> ${esc(w.translation)}</p><p><strong>Collocations :</strong> ${esc(w.collocations)}</p><p><strong>Signal SRS :</strong> ${score>=70?'fort — une bonne note SRS peut maintenant espacer davantage la carte.':'à renforcer — le SRS évitera de l’espacer trop vite.'}</p></div>`;renderHeader()
  }
  function newHunt(){if(VOCAB.length<4)return;const answer=currentWord(),pool=VOCAB.filter((_,i)=>i!==(state.current%VOCAB.length)).sort(()=>Math.random()-.5).slice(0,3),choices=[answer,...pool].sort(()=>Math.random()-.5);$('#huntQuestion').textContent=`🇫🇷 ${answer.translation}`;$('#huntChoices').innerHTML=choices.map(w=>`<button data-answer="${esc(w.word)}">${esc(w.word)}</button>`).join('');$('#huntFeedback').innerHTML='';$$('#huntChoices button').forEach(b=>b.addEventListener('click',()=>{const ok=b.dataset.answer===answer.word;state.stats.hunts++;state.xp+=ok?15:3;if(ok)state.stats.correct++;save();$('#huntFeedback').innerHTML=ok?'<p>🟢 Correct !</p>':`<p>🔴 La réponse était <strong>${esc(answer.word)}</strong>.</p>`;renderHeader()}))}
  function renderStory(){const w=currentWord();$('#storyText').innerHTML=`<div class="info"><div><b>🇮🇹 ITALIANO</b>${esc(w.story)}</div><div><b>🇫🇷 FRANÇAIS</b>${esc(w.storyFr)}</div><div><b>🎯 MOT CIBLE</b>${esc(w.word)} — ${esc(w.translation)}</div></div>`}
  function speak(text){if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='it-IT';u.rate=.88;speechSynthesis.speak(u)}}
  function renderStats(){const total=VOCAB.length,known=Object.values(state.known).filter(Boolean).length,pct=total?Math.round(known/total*100):0;$('#statsTitle').textContent=`${known} / ${total} mots actifs maîtrisés`,$('#bar').style.width=pct+'%';const rs=Object.values(state.reviews),avgEase=rs.length?(rs.reduce((a,r)=>a+(r.ease||2.5),0)/rs.length).toFixed(2):'—';$('#statsText').innerHTML=`${pct}% du parcours initial. ${state.stats.seen} évaluations SRS, ${state.stats.blurts} blurtings, ${state.stats.productions} productions orales et ${state.stats.stories} stories.<br><br>🔄 <strong>Intervalle moyen :</strong> ${rs.length?(rs.reduce((a,r)=>a+(r.interval||0),0)/rs.length).toFixed(1)+' jours':'—'}<br>🧠 <strong>Facilité moyenne :</strong> ${avgEase}<br>📅 <strong>À revoir :</strong> ${dueCount()} · 🆕 <strong>Nouveaux :</strong> ${newCount()}`}
  function bind(){updateStreak();$$('[data-go]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.go)));$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>renderTab(b.dataset.tab)));$$('[data-grade]').forEach(b=>b.addEventListener('click',()=>gradeCurrent(Number(b.dataset.grade))));$$('.mood').forEach(b=>b.addEventListener('click',()=>{$$('.mood').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mood=b.dataset.mood;$('#moodLabel').textContent=b.textContent.replace(/^\S+\s/,'');save()}));$('#next')?.addEventListener('click',()=>{state.current=nextCardIndex();save();renderLearn()});$('#mapWord')?.addEventListener('change',e=>{state.current=Number(e.target.value);drawMap(state.current)});$('#blurtCheck')?.addEventListener('click',blurtCheck);$('#storySpeak')?.addEventListener('click',()=>speak(currentWord().story));renderHeader();renderLearn()}
  document.addEventListener('DOMContentLoaded',bind);
})();
