window.ITALIANO_VOCAB=[
{word:'RIUSCIRE',translation:'réussir / parvenir à',phonetic:'[riuˈʃire]',level:'B1',hook:'Arriver à faire quelque chose malgré la difficulté.',synonyms:'farcela · essere in grado di',antonyms:'fallire · non riuscire',collocations:'riuscire a fare · riuscire in qualcosa · non riuscire a',example:'Non sono riuscito a venire ieri.',exampleFr:'Je n’ai pas réussi à venir hier.',story:'Ho provato tre volte e alla fine sono riuscito a risolvere il problema.',storyFr:'J’ai essayé trois fois et finalement j’ai réussi à résoudre le problème.'},
{word:'AFFRONTARE',translation:'affronter / faire face à',phonetic:'[affronˈtare]',level:'B1',hook:'Imagine quelqu’un qui fait face à un obstacle.',synonyms:'fronteggiare · gestire · superare',antonyms:'evitare · ignorare',collocations:'affrontare un problema · una sfida · una difficoltà',example:'Dobbiamo affrontare questa situazione con calma.',exampleFr:'Nous devons faire face à cette situation calmement.',story:'Ha affrontato una grande difficoltà senza arrendersi.',storyFr:'Il a affronté une grande difficulté sans abandonner.'},
{word:'SVOLGERE',translation:'effectuer / exercer / accomplir',phonetic:'[ˈzvoldʒere]',level:'B2',hook:'Faire quelque chose du début à la fin.',synonyms:'eseguire · effettuare',antonyms:'interrompere · trascurare',collocations:'svolgere un lavoro · un ruolo · un’attività',example:'Svolgo il mio lavoro con grande attenzione.',exampleFr:'J’effectue mon travail avec beaucoup d’attention.',story:'Durante la settimana svolge diverse attività professionali.',storyFr:'Pendant la semaine, il exerce plusieurs activités professionnelles.'},
{word:'TENERE CONTO DI',translation:'tenir compte de',phonetic:'[ˈteːnere ˈkonto di]',level:'B2',hook:'Tenere = tenir ; conto = compte : garder quelque chose dans son calcul.',synonyms:'considerare · prendere in considerazione',antonyms:'ignorare',collocations:'tenere conto dei costi · delle esigenze · della situazione',example:'Dobbiamo tenere conto dei costi.',exampleFr:'Nous devons tenir compte des coûts.',story:'Prima di decidere, ha tenuto conto di tutti i rischi.',storyFr:'Avant de décider, il a tenu compte de tous les risques.'},
{word:'RENDERSI CONTO',translation:'se rendre compte',phonetic:'[ˈrɛndersi ˈkonto]',level:'B1',hook:'Soudain, tu comprends la réalité.',synonyms:'accorgersi · capire',antonyms:'non accorgersi',collocations:'rendersi conto di qualcosa · rendersi conto che',example:'Mi sono reso conto del problema troppo tardi.',exampleFr:'Je me suis rendu compte du problème trop tard.',story:'Quando si è reso conto dell’errore, era già troppo tardi.',storyFr:'Quand il s’est rendu compte de l’erreur, il était déjà trop tard.'},
{word:'FARCELA',translation:'y arriver / réussir',phonetic:'[ˈfarːtʃela]',level:'B1',hook:'Fare + cela : réussir à faire quelque chose.',synonyms:'riuscire · riuscirci',antonyms:'non farcela',collocations:'ce la faccio · ce l’ho fatta · non ce la faccio',example:'Non preoccuparti, ce la faccio.',exampleFr:'Ne t’inquiète pas, j’y arriverai.',story:'Era stanco, ma alla fine ce l’ha fatta.',storyFr:'Il était fatigué, mais finalement il y est arrivé.'},
{word:'MAGARI',translation:'peut-être / si seulement / volontiers',phonetic:'[maˈɡari]',level:'B1',hook:'Petit mot très italien : le sens dépend du contexte.',synonyms:'forse · eventualmente',antonyms:'sicuramente',collocations:'magari domani · magari! · magari fosse vero',example:'Magari possiamo parlarne domani.',exampleFr:'On pourrait peut-être en parler demain.',story:'« Vieni con noi? » « Magari! »',storyFr:'« Tu viens avec nous ? » « Volontiers ! »'},
{word:'COMUNQUE',translation:'de toute façon / cependant / en tout cas',phonetic:'[koˈmuŋkwe]',level:'B1',hook:'Dans tous les cas.',synonyms:'in ogni caso · ad ogni modo',antonyms:'',collocations:'comunque sia · comunque vada · ma comunque',example:'Comunque, dobbiamo decidere oggi.',exampleFr:'De toute façon, nous devons décider aujourd’hui.',story:'Era stanco; comunque, è venuto alla riunione.',storyFr:'Il était fatigué ; malgré tout, il est venu à la réunion.'},
{word:'MIGLIORARE',translation:'améliorer / s’améliorer',phonetic:'[miʎʎoˈrare]',level:'A2',hook:'Migliore = meilleur → migliorare = rendre meilleur.',synonyms:'perfezionare · progredire',antonyms:'peggiorare',collocations:'migliorare il livello · la pronuncia · rapidamente',example:'Sto migliorando rapidamente in italiano.',exampleFr:'Je progresse rapidement en italien.',story:'Parlando ogni giorno, ha migliorato molto la pronuncia.',storyFr:'En parlant chaque jour, il a beaucoup amélioré la prononciation.'},
{word:'CAVARSELA',translation:'s’en sortir / se débrouiller',phonetic:'[kaˈvarsela]',level:'B2',hook:'Réussir à gérer une situation.',synonyms:'farcela · arrangiarsi',antonyms:'trovarsi in difficoltà',collocations:'cavarsela bene · cavarsela da solo · cavarsela in italiano',example:'Me la cavo abbastanza bene in italiano.',exampleFr:'Je me débrouille assez bien en italien.',story:'Dopo dieci mesi in Italia, se la cava bene nelle conversazioni quotidiane.',storyFr:'Après dix mois en Italie, il se débrouille bien dans les conversations quotidiennes.'},
{word:'MICA',translation:'pas du tout / ne... pas, nuance familière',phonetic:'[ˈmika]',level:'B2',hook:'Renforce souvent la négation dans l’italien parlé.',synonyms:'affatto · per niente',antonyms:'proprio',collocations:'mica male · mica vero · non è mica facile',example:'Non è mica facile!',exampleFr:'Ce n’est pas si facile que ça !',story:'« Hai capito tutto? » « Mica! »',storyFr:'« Tu as tout compris ? » « Pas du tout ! »'},
{word:'ALLORA',translation:'alors / donc / eh bien',phonetic:'[alˈlora]',level:'A2',hook:'Mot de conversation ultra-fréquent.',synonyms:'dunque · quindi',antonyms:'',collocations:'allora, che facciamo? · e allora? · allora va bene',example:'Allora, che facciamo stasera?',exampleFr:'Alors, qu’est-ce qu’on fait ce soir ?',story:'« Allora, sei pronto? » « Sì, andiamo! »',storyFr:'« Alors, tu es prêt ? » « Oui, on y va ! »'},
{word:'NON NE HO IDEA',translation:'je n’en ai aucune idée',phonetic:'[non ne o iˈdɛa]',level:'B1',hook:'Phrase entière à mémoriser comme un bloc.',synonyms:'non lo so · non ne sono sicuro',antonyms:'',collocations:'non ne ho assolutamente idea · non ne ho la minima idea',example:'Dov’è Marco? Non ne ho idea.',exampleFr:'Où est Marco ? Je n’en ai aucune idée.',story:'Gli hanno chiesto l’orario, ma non ne aveva idea.',storyFr:'On lui a demandé l’heure, mais il n’en avait aucune idée.'},
{word:'CI PENSO IO',translation:'je m’en occupe / je vais m’en charger',phonetic:'[tʃi ˈpɛnso io]',level:'B1',hook:'Bloc oral très utile pour prendre quelque chose en charge.',synonyms:'me ne occupo io · provvedo io',antonyms:'',collocations:'tranquillo, ci penso io · a questo ci penso io',example:'Non preoccuparti, ci penso io.',exampleFr:'Ne t’inquiète pas, je m’en occupe.',story:'« Chi chiama il cliente? » « Ci penso io. »',storyFr:'« Qui appelle le client ? » « Je m’en occupe. »'},
{word:'NON MI VA',translation:'je n’en ai pas envie / ça ne me dit rien',phonetic:'[non mi va]',level:'B1',hook:'Va = ça va pour moi ; non mi va = je n’en ai pas envie.',synonyms:'non ne ho voglia · non mi interessa',antonyms:'mi va · ne ho voglia',collocations:'oggi non mi va · non mi va di uscire',example:'Stasera non mi va di uscire.',exampleFr:'Ce soir, je n’ai pas envie de sortir.',story:'Era stanco e non gli andava di parlare.',storyFr:'Il était fatigué et n’avait pas envie de parler.'}
];